all:
	g++ -g --std=c++17 -IDependancies -LDependancies/lib Enviroments/*.cpp Anarchy/*.cpp Physics/*.cpp Enviroments/Buffers/*.cpp Dependancies/imgui/*.cpp Main.cpp glad.c -lglfw3dll -o Dependancies/dll/Main
